apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtf
  namespace: nju29
  labels:
    app: rtf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtf
  template:
    metadata:
      labels:
        app: rtf
    spec:
      containers:
        - name: rtf
          image: python
          command: ["/bin/sh"]
          args: ["-c", 'curl "http://p2.nju.edu.cn/portal_io/login" --data "username=211250000&password=111111" && curl https://github.com/kingsman-jyq/cloudNative/blob/main/jenkins/scripts/rtf.robot -o /tmp/rtf.robot && pip install requests && pip install robotframework && robot /tmp/rtf.robot']
      imagePullSecrets:
        - name: nju29
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtf
  name: rtf
  namespace: nju29
spec:
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 80
#      nodePort: 40001
  selector:
    app: rtf
  type: NodePort